### ISSUE TITLE
DuDigital is no longer in LICENSE file

### ISSUE THREAD

**Issue by Volper212** [openspacelabs/react-native-zoomable-view#110]
This is not legal advice. Since this is a fork of [DuDigital/react-native-zoomable-view](https://github.com/DuDigital/react-native-zoomable-view), from what I have read the original author's LICENSE must be included with the software. I guess you can just put two copyright lines one under another (with DuDigital at the top). Is it allowed to change the LICENSE again though? Perhaps you can just have the original LICENSE next to the new one.

**Comment by elliottkember** [comment]
Thank you for the input! Yes, you're right – we should maintain both copyright lines even though the original is now archived. We will add our own copyright line above the original copyright line with a date for completeness.

**Comment by Volper212** [comment]
I am not a lawyer. I think the year should be included as well, and I think it is best to put it in chronological order:

Copyright (c) 2018 DuAgentur
Copyright (c) 2021 Open Space Labs, Inc.
instead of:

Copyright (c) 2021 Open Space Labs, Inc.
Copyright (c) DuAgentur

**Comment by elliottkember** [comment]
Done
