### ISSUE TITLE
How do I determine which element is pressed?

### ISSUE THREAD

**Issue by Volper212** [openspacelabs/react-native-zoomable-view#112]
`onSingleTap` gives a `target`, which is a node id of the pressed element and is difficult to make use of. `Pressable` inside the `ReactNativeZoomableView` does not do the trick either.

**Comment by Volper212** [comment]
Alright, `target` is usable in Android with `findViewById` or `requireViewById`. Still a hacky solution, though.

**Comment by thomasttvo** [comment]
Tapping on subelements (like pins) are tricky. Especially when they can overlap or are too close to each other. We recommend using https://github.com/mourner/rbush-knn to detect tap location and select the right component accordingly
