### ISSUE TITLE
zoomEnabled not working

### ISSUE THREAD

**Issue by keung7251** [openspacelabs/react-native-zoomable-view#13]
zoomEnabled not working

**Comment by felixchan** [comment]
+1 Not working for me as well.

**Comment by liquidvisual** [comment]
+1  kind of a deal breaker :(

**Comment by elevyg** [comment]
same here

**Comment by thomasttvo** [comment]
Will be fixed in https://github.com/openspacelabs/react-native-zoomable-view/pull/34/files
