### ISSUE TITLE
Always on top?

### ISSUE THREAD

**Issue by sstephans** [openspacelabs/react-native-zoomable-view#20]
I can't seem to find any information about this in the docs, but I'm trying to get my zoomable view to always be on top of other components when the zoom causes them to overlap. This doesn't seem to be the case by default. Setting the zIndex in the style props of the zoomable view doesn't work either. 

Do you have a solution on how to implement this?

**Comment by thomasttvo** [comment]
Are you trying to achieve something like this?
```tsx
<>
	<SomeComponent key={'some-component'}/>
    <View style={StyleSheet.absoluteFill}>
		<ZoomableView key={'zoomable-view'}/>
	</View>
</>
```
