### ISSUE TITLE
PanResponder doesn't begin when TouchableOpacity is inside

### ISSUE THREAD

**Issue by felixchan** [openspacelabs/react-native-zoomable-view#23]
```
<ReactNativeZoomableView >
    <TouchableOpacity
    onPress={() => {}}
    >
        <View style={{ width: 60, height: 60}}/>
    </TouchableOpacity>
</ReactNativeZoomableView
```

Is there a way to enable dragging when the user initially touches the child view? The dragging currently works when the user is outside the child view.

**Comment by professorkolik** [comment]
@felixchan I am not the maintainer but spend a lot of times with this library. Though I think it's impossible to have TouchableOpacity inside ReactNativeZoomableView.

Can you give some example of usecase?

**Comment by elliottkember** [comment]
I don't think this is currently possible, sorry. The event is captured by the TouchableOpacity.

**Comment by thomasttvo** [comment]
This is an interesting use case. We'll think about supporting it in the later versions. For now, the best solution is detect the tap position and respond accordingly.
