### ISSUE TITLE
Reset Zoom Level after State Refresh

### ISSUE THREAD

**Issue by EricLi35** [openspacelabs/react-native-zoomable-view#26]
I am implementing a dropdown menu where the user can select one of three pictures. I was wondering how you can reset the zoom level upon selecting another picture. The issue is that if I zoom into a picture and select a different picture, the same zoom level is still there for the new picture. I have experimented with initialZoom already and that didn't seem to work. 

Thanks in advance for any help/suggestions

**Comment by elliottkember** [comment]
@EricLi35 Have you tried setting a `key` on the component? Changing the `key` of a React component will cause it to re-mount. Re-mounting might do the trick!

**Comment by EricLi35** [comment]
Hi, thanks for the reply. I ended up finding an alternate method by moving the ReactNativeZoomableView into a closer layer.

**Comment by esadkrs** [comment]
Hey @EricLi35 , can you please share your method?

**Comment by thomasttvo** [comment]
You can also use `ref.zoomTo(1)` https://github.com/openspacelabs/react-native-zoomable-view#methods
