### ISSUE TITLE
Is there a way to "disable" the tapping on ReactNativeZoomableView?

### ISSUE THREAD

**Issue by EricLi35** [openspacelabs/react-native-zoomable-view#27]
I have a ReactNativeZoomableView wrapping around and Svg, which wraps the Circle. The code structure looks something similar to 
`<ReactNativeZoomableView >
            <Svg >
                <Circle onPress={() => Alert.alert("Circle has been tapped")} />
            </Svg>
</ReactNativeZoomableView>`.

The issue is that if I tap on the Circle, the onPress handler from Circle won't be called, because ReactNativeZoomableView is "in the way".

I appreciate any solutions/workarounds to this problem, thanks so much in advance

**Comment by maartenvandillen** [comment]
Hi @EricLi35 did you solve this? I'm having the opposite problem. My onPress is working fine on the SVG element (path) but I can't pan when dragging with one finger. That only works outside the SVG path.

**Comment by Volper212** [comment]
Perhaps you will find #112 useful.
