### ISSUE TITLE
Make animated touch feedback optional? 

### ISSUE THREAD

**Issue by danweav1** [openspacelabs/react-native-zoomable-view#28]
Hello, is it possible to make the animated touch feedback optional (the small gray circle that appears when tapping/double tapping)? It is implemented with the `AnimatedTouchFeedback` component. Thanks!

**Comment by charlesx2013** [comment]
+1 on this!

**Comment by elevyg** [comment]
+2 !

**Comment by i-ira** [comment]
+1000000... any unnecessary UI quirk should always be optional.

**Comment by thomasttvo** [comment]
👌  will be part of this release https://github.com/openspacelabs/react-native-zoomable-view/pull/34/files
