### ISSUE TITLE
How to keep to new position of the zoomable view after the pan movement ends?

### ISSUE THREAD

**Issue by medmo7** [openspacelabs/react-native-zoomable-view#30]
Thank you for this great library. I have a question, i would like to be able to drag an image and keep the new positon of the image (inside the boundaries)
here is how I use the component:
```javascript

	<ReactNativeZoomableView
		ref={zoomableRef}
		maxZoom={1}
	        minZoom={0.3}
		zoomStep={0.1}
		initialZoom={1}
		bindToBorders={true}>					
	<Image source={{ uri: currentQuestion.question_image }} resizeMode='contain' style={{ height: '100%', width: '100%' }} />
	   </ReactNativeZoomableView>
```

**Comment by thomasttvo** [comment]
@medmo7 you can refer to this example https://github.com/openspacelabs/react-native-zoomable-view#example
