### ISSUE TITLE
Pan on ios has jumpy behavior

### ISSUE THREAD

**Issue by rdreasn** [openspacelabs/react-native-zoomable-view#33]
Jumpy position while panning/dragging on ios (tested on ios 15.4).

**Comment by thomasttvo** [comment]
Are you using simulator on an M1 mac? React Native Animation doesn't work too well with M1s. Try it on a real device.

**Comment by bergkamp** [comment]
Same problem when I use M1 mac + real device ( iPhone13 )

**Comment by thomasttvo** [comment]
@bergkamp does it happen with the example expo app?

**Comment by bergkamp** [comment]
Thanks @thomasttvo 

I try to run example on my device , got this error:

> iOS Bundling failed 334ms
>  Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/zhrs/workshop/bergkamp/react-> 
>  native-zoomable-view/src/index.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project.

> If you are sure the module exists, try these steps:
>  1. Clear watchman watches: watchman watch-del-all
>  2. Delete node_modules and run yarn install
>  3. Reset Metro's cache: yarn start --reset-cache
>  4. Remove the cache: rm -rf /tmp/metro-*
> 1 | import ReactNativeZoomableView from './ReactNativeZoomableView';
>  2 | import ReactNativeZoomableViewWithGestures from './ReactNativeZoomableViewWithGestures';
>  3 | import { ReactNativeZoomableViewProps, ZoomableViewEvent } from './typings';
>  4 |

This is my project running on iPhone13 (iOS 15.4.1)

Double tap on the photo

https://user-images.githubusercontent.com/36283/167333271-769d1a14-e460-4ff4-8514-5f58c43614e6.mov

**Comment by thomasttvo** [comment]
@bergkamp try again using this snack https://snack.expo.dev/@thomasttvo/e5b899. Do you still see the problem?

**Comment by bergkamp** [comment]
> @bergkamp try again using this snack https://snack.expo.dev/@thomasttvo/e5b899. Do you still see the problem? 

Perfect
https://user-images.githubusercontent.com/36283/167973929-cf1a0048-3584-4b15-9b07-be9f0824369b.MOV

**Comment by rdreasn** [comment]
It's still the same on my simulator (M1 mac) and I don't have access to test to real device.
I ended up not using getPanMomentumDecayAnim() from source code.

**Comment by rdreasn** [comment]
> https://snack.expo.dev/@thomasttvo/e5b899

the snack working fine.
But it's still the same on my simulator (M1 mac) and I don't have access to test to real device.
I ended up not using getPanMomentumDecayAnim() from source code.

**Comment by thomasttvo** [comment]
@bergkamp if the snack works fine then it's probably something to do with your local code. Also try replacing the image on the snack to see if the problem can be reproduced.

@rdreasn that's gonna be tricky if you don't have access to a real iOS device. React Native's built-in animation doesn't play well with M1. That said, we're gonna switch to reanimated in `v3` so you'll be able to test it on your simulator then. Stay tuned!

For now, I'll close this thread. Let me know if you have any other issues
