### ISSUE TITLE
pan issue on ios 

### ISSUE THREAD

**Issue by Lobnachour** [openspacelabs/react-native-zoomable-view#36]
pan doesn't work properly on IOS.

**Comment by thomasttvo** [comment]
Is this related to #33?

**Comment by Lobnachour** [comment]
No it's not related to #33. It doesn't have a jumpy behavior on IOS, the issue is that I can't pan throughout all the image in IOS, on android it works perfectly fine.

**Comment by thomasttvo** [comment]
Does the expo snack work for you? https://snack.expo.dev/@thomasttvo/eaf257
