### ISSUE TITLE
Disable Panning when Zoom 1

### ISSUE THREAD

**Issue by sebasptsch** [openspacelabs/react-native-zoomable-view#38]
It should be possible to disable panning when the image has not yet been zoomed into. This is useful when using with libraries like ['react-native-pager-view'](https://github.com/callstack/react-native-pager-view)

**Comment by mmahandev** [comment]
Is there some way to disable panning at all?

**Comment by kimho** [comment]
This may be a trick, but setting the movementSensibility value to a very high value can solve the issue.

```
<ReactNativeZoomableView
    ref={zoomableViewRef}
    zoomEnabled={true}
    movementSensibility={movementSensibility}

    onStartShouldSetPanResponder={(event, gestureState, zoomableViewEventObject) => {
      if(zoomableViewEventObject.zoomLevel==1 && movementSensibility != 1000000000) {
        console.log('set move sensibility 1000000');
        setMovementSensibility(1000000000);
      } 
    }}

    onPanResponderMove={(event, gestureState, zoomableViewEventObject) => {
      if(zoomableViewEventObject.zoomLevel != 1 && movementSensibility != 1) {
        setMovementSensibility(1);
      }
    }}

    onZoomEnd={() => {
      zoomableViewRef.current.zoomTo(1);
    }}
    ...
  ...

```

**Comment by RayHughes** [comment]
Request feature as well

**Comment by danielreuterwall** [comment]
I've made a fork to implement this. It seems to work ok, cdf1b1c47017e37951b63f29674df8b5b1c89fc1?
Can make a pull request, what do you think?

**Comment by janpe** [comment]
Hoping to see this feature as well. @danielreuterwall maybe you should go ahead and open the pull request to get this moving?

**Comment by janpe** [comment]
@danielreuterwall or maybe it could be just a `panEnabled` (default true) prop where you can determine yourself when it should be enabled or disabled. Similar to `zoomEnabled` on `react-native-pager-view` which was mentioned in the initial message of this issue.

**Comment by danielreuterwall** [comment]
I agree, having a `panEnabled` is a more flexible solution. Although this feels like a very common requirement that is could justify a dedicated prop. I'll try to fix a PR this week.

**Comment by sebasptsch** [comment]
> I agree, having a `panEnabled` is a more flexible solution. Although this feels like a very common requirement that is could justify a dedicated prop. I'll try to fix a PR this week.

Thanks for taking a look!

**Comment by janpe** [comment]
Hi again @danielreuterwall! Do you have an idea when you might have time to continue this one?

**Comment by danielreuterwall** [comment]
Just added a PR for the fix I made. Haven't continued with the `panEnabled` prop but that would be a natural continuation.

**Comment by tauntmachine** [comment]
would someone be kind enough to approve this??

**Comment by manarfalah** [comment]
is there any way to disable panning beyond edges also when zooming ? I am using disablePanOnInitialZoom but I want this behavior also when I zoom and get to edge of image.
