### ISSUE TITLE
Second double tap

### ISSUE THREAD

**Issue by BaronHandsome** [openspacelabs/react-native-zoomable-view#39]
Hi. Is it possible to make double-tap again return the original size of the image and not continue to increase it?

**Comment by dan-doyon-endear** [comment]
Would like to have this feature or recipe to do this too.

**Comment by elliottkember** [comment]
This is a good idea. 

We currently use it as a "map" style component, where users can keep zooming in, but I can imagine a prop like `zoomMode: map" | "image"` that could determine whether it zooms in further or resets to zero.

**Comment by thomasttvo** [comment]
@BaronHandsome you can try setting the maxZoom a little lower. Double tapping will revert back to 1 if it already reaches maxZoom.
