### ISSUE TITLE
[NOT ERROR] Component in web is showing not found types warning

### ISSUE THREAD

**Issue by elenitaex5** [openspacelabs/react-native-zoomable-view#67]
Hello,
I'm using the component in three platforms. iOS, Android and web. 
Is working fine in both iOS and Android but showing a WARNING (not error) in web.
<img width="1093" alt="image" src="https://github.com/openspacelabs/react-native-zoomable-view/assets/14013852/f00b506e-732b-4f47-af09-5edfe0022026">

I'm using EXPO with webpack.

**Comment by elenitaex5** [comment]
Hey @elliottkember when there's gonna be a release fixing this? because the problem still persist in 2.1.1. And there's no new code or version to include fixing this.

**Comment by elenitaex5** [comment]
Last release was in 21th October 2022. I don't understand why you merge PRs solving problems and never has new releases no github nor npm

**Comment by elliottkember** [comment]
@elenitaex5 Done. Thanks for the reminder.

**Comment by elenitaex5** [comment]
@elliottkember thanks! I've just upgrade my dependency and Warning messages are gone. Thanks!
