### ISSUE TITLE
onShouldBlockNativeResponder

### ISSUE THREAD

**Issue by lukahc** [openspacelabs/react-native-zoomable-view#71]
Currently the zoomable view conflicts with other packages like [react native tab view](https://github.com/react-navigation/react-navigation) because of line 130 in `src/ReactNativeZoomableView.tsx`:

`      onShouldBlockNativeResponder: () => false,
`

This line can lead to the `PanResponder` being terminated if there are other instances of `PanResponder`, meaning that the zoomable view can't pan or zoom properly, if at all. Could you please fix this, either by changing `false` to `true`, or just by making `onShouldBlockNativeResponder` an optional prop?

**Comment by elliottkember** [comment]
Hi! This sounds like a great candidate for a pull request. If you are able to fix the problem in a PR, please submit it and we'll take a look.

**Comment by elliottkember** [comment]
@lukahc Thank you for the help! Turns out I needed this functionality almost immediately. Very useful.

Do you think this should be `true` by default? It seems like it would always be a good idea for it to block pan responders.

**Comment by lukahc** [comment]
> @lukahc Thank you for the help! Turns out I needed this functionality almost immediately. Very useful.
> 
> Do you think this should be `true` by default? It seems like it would always be a good idea for it to block pan responders.

I agree, I can't think of many scenarios where it would be better for it to be `false`, I can make a PR for that change

**Comment by lukahc** [comment]
@elliottkember https://github.com/openspacelabs/react-native-zoomable-view/pull/75

**Comment by elliottkember** [comment]
Nice – I think that should be fine.

An interesting note: `onShouldBlockPanResponder` is only implemented on Android.

However, I found that it was working on iOS too, but only because I happened to be using a `react-native-gesture-handler` wrapper. That library overrides UIManager to make this work. More info here: https://github.com/facebook/react-native/pull/40750
