### ISSUE TITLE
Disable Pan move like zoomEnabled

### ISSUE THREAD

**Issue by BrunoBross** [openspacelabs/react-native-zoomable-view#84]
Its possible to disable Pan gesture like zoomEnabled?

**Comment by raulTeoSalinas** [comment]
Did you find an alternative? Im trying to disable pan too. It would be very helpful when dealing with other gesture handlers components inside `ReactNativeZoomableView`.

**Comment by BrunoBross** [comment]
@raulTeoSalinas if you remove "this.zoomLevel === this.props.initialZoom" condition (there are two conditions) inside ReactNativeZoomableView (node_modules) and set disablePanOnInitialZoom={true} (component), the pan will be disabled but you will be able to zoom
