### ISSUE TITLE
Need onStartShouldSetPanResponderCapture to steal PanResponder from Childs

### ISSUE THREAD

**Issue by easy-bios** [openspacelabs/react-native-zoomable-view#91]
The missing onStartShouldSetPanResponderCapture prop makes it impossible to steal PanResponder on Move if Child has a Pressable:
https://stackoverflow.com/questions/75975994/react-native-zoomable-view-child-component-should-have-onpress-and-be-pannable

To fix this we need onStartShouldSetPanResponderCapture as an Prop.

**Comment by elliottkember** [comment]
This sounds like a good idea – please open a pull request with the changes and we'll review it. Thank you!

**Comment by easy-bios** [comment]
This is my first time contributing somewhere. Please give me some advice if there is something wrong with the pill request. ;)

https://github.com/openspacelabs/react-native-zoomable-view/pull/93

**Comment by DanielKuhn** [comment]
I'm having the exact same problem (Pressable inside zoomable view consumes pan event) and don't understand the solution outlined here. Could someone explain, please?

**Comment by DanielKuhn** [comment]
solved in #101
