### ISSUE TITLE
_couldCallSwipeEvent() returns false when not all props are provided

### ISSUE THREAD

**Issue by jaredbothwell** [openspacelabs/react-native-zoomable-view#96]
`onSwipe`, `onSwipeUp`, `onSwipeDown`,  `onSwipeLeft`,  and `onSwipeRight` are all optional props for `ReactNativeZoomableViewWithGestures` but this [line](https://github.com/openspacelabs/react-native-zoomable-view/blob/d4d14bf34a8365b420107426a8e2bbc8476b9a10/src/ReactNativeZoomableViewWithGestures.tsx#L57) returns false if any one of these props is not provided. Since these props are optional would it make sense to not require them for `_couldCallSwipeEvent()` to return true by using `||` instead of `&&`

**Comment by elliottkember** [comment]
That sounds right to me. Would you mind making a quick PR for that?

**Comment by jaredbothwell** [comment]
Yeah I can make PR for it
