### ISSUE TITLE
Error ReactNativeZoomableViewProps

### ISSUE THREAD

**Issue by dinhsuu** [openspacelabs/react-native-zoomable-view#99]
I installed the package and encountered an error like this: Exporting local "ReactNativeZoomableViewProps", which is not declared. please help me

![Simulator Screenshot - iPhone X - 2024-04-14 at 11 22 23](https://github.com/openspacelabs/react-native-zoomable-view/assets/39111165/9cb3eb77-08de-4ee3-a649-7fabfba6d4e1)

**Comment by vasteez** [comment]
@dinhsuu how did you resolve this? I am experiencing the same issue
